language: node_js
sudo: required
dist: trusty

before_install:
  - node --version | grep -q 'v0.8' && npm install -g npm@2 || true

node_js:
  - "4.0.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs"
  - "iojs-v2"
